### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by aggrand** [benc-uk/kube-workshop#9]
Hello, I am interested in using this workshop, but have some changes I'd like to make. I'd be interested in forking this repo, making those changes, and then distributing the instructions to workshop attendees (with citation of the original source). Would it be possible to add a license that allows this?

**Comment by aggrand** [comment]
cc @benc-uk I believe is the owner!

**Comment by benc-uk** [comment]
Hey, would an MIT license cover what you need? 
I believe it would

**Comment by aggrand** [comment]
Yes I believe an MIT license would be perfect!

**Comment by benc-uk** [comment]
MIT license added
